# Generated by Django 4.2.7 on 2023-11-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playround', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='porcentaje_seguidores',
        ),
        migrations.AddField(
            model_name='candidato',
            name='numero_listas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
