# Generated by Django 4.2.7 on 2023-11-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playround', '0002_remove_candidato_porcentaje_seguidores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='p_favoritos',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='p_listas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='p_seguidores',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
